version: '3.8'

networks:
  docker-private-network:
    driver: bridge

volumes:
  postgres-data:

services:
  backend:
    container_name: backend
    build: ./server/Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - docker-private-network
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clients
    ports:
      - 5432:5432
    networks:
      - docker-private-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    image: nginx:latest
    restart: always
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - docker-private-network
    ports:
      - 80:80
